// Copies the repo README and the API's OpenAPI spec into the web app so the
// /docs page renders them. Run after editing either: `npm run sync:docs`.
// (Generated files are committed, so Vercel doesn't need files outside apps/web.)
import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';

const readme = readFileSync('../../README.md', 'utf8');
writeFileSync(
  'src/content/readme.generated.ts',
  `// Generated by scripts/sync-docs.mjs from /README.md — do not edit.\nconst readme = ${JSON.stringify(readme)};\nexport default readme;\n`,
);
copyFileSync('../api/openapi.json', 'src/content/openapi.json');
console.log('Synced README.md and openapi.json into src/content/');
