/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_markAllRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["NotificationsController_markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and get tokens. */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new token pair (the old refresh token stops working). */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session's refresh token. */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_hosting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/rsvps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_rsvps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming published events (cursor-paginated). Public. */
        get: operations["EventsController_list"];
        put?: never;
        /** Create an event. You become its host. */
        post: operations["EventsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the event as an iCalendar (.ics) file for Google, Apple or Outlook calendars. */
        get: operations["EventsController_calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one event. Send a token to also get `myRsvpStatus`. */
        get: operations["EventsController_findOne"];
        put?: never;
        post?: never;
        /** Cancel (soft-delete) an event. Host only. */
        delete: operations["EventsController_remove"];
        options?: never;
        head?: never;
        /** Edit an event. Host only. */
        patch: operations["EventsController_update"];
        trace?: never;
    };
    "/api/v1/events/{id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * RSVP to an event. Returns `going` if you got a seat, otherwise `waitlisted`.
         *     Safe to retry — calling it twice never double-books.
         */
        post: operations["RsvpsController_join"];
        /** Cancel your RSVP. Your seat goes to the next person on the waitlist. */
        delete: operations["RsvpsController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The waitlist, in the order people will be promoted. Host only. */
        get: operations["RsvpsController_waitlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/attendees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People going to this event, in the order they got their seat. Public. */
        get: operations["RsvpsController_attendees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NotificationResponse: {
            /** @enum {string} */
            type: "event_reminder" | "waitlist_promoted" | "event_updated" | "event_cancelled";
            id: string;
            title: string;
            body: string;
            /** @description Event this notification is about, if any */
            eventId: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationPage: {
            items: components["schemas"]["NotificationResponse"][];
            unreadCount: number;
        };
        RegisterDto: {
            /**
             * Format: email
             * @example you@example.com
             */
            email: string;
            /**
             * @description At least 8 characters.
             * @example Password123!
             */
            password: string;
            /** @example Asha Rao */
            name: string;
        };
        PublicUser: {
            id: string;
            email: string;
            name: string;
        };
        AuthTokensResponse: {
            accessToken: string;
            refreshToken: string;
            /** @description Access-token lifetime in seconds */
            expiresIn: number;
            user: components["schemas"]["PublicUser"];
        };
        LoginDto: {
            /**
             * Format: email
             * @example demo@events.dev
             */
            email: string;
            /** @example Password123! */
            password: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        MeResponse: {
            id: string;
            email: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Events you host (not cancelled) */
            hostingCount: number;
            /** @description Events you're going to */
            goingCount: number;
        };
        HostResponse: {
            id: string;
            name: string;
        };
        EventResponse: {
            /** @enum {string} */
            status: "draft" | "published" | "cancelled";
            /** @enum {string} */
            category: "tech" | "music" | "food" | "sports" | "arts" | "networking" | "outdoors" | "other";
            /** @description The online link. Present only for the host and people going. */
            meetingUrl?: string | null;
            /**
             * @description The caller's RSVP status — present only when a valid token is sent.
             * @enum {string|null}
             */
            myRsvpStatus?: "going" | "waitlisted" | "cancelled" | null;
            id: string;
            title: string;
            description: string | null;
            location: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            capacity: number | null;
            goingCount: number;
            /** @description null when capacity is unlimited */
            seatsLeft: number | null;
            version: number;
            /** @description Minutes before start that attendees get a reminder; null = none */
            reminderMinutes: number | null;
            /** @description True if the event has an online link (the link itself may be hidden from you) */
            hasMeetingLink: boolean;
            host: components["schemas"]["HostResponse"];
            /** @description Names of the first few people going (for avatar stacks) */
            attendeePreview: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MyEventsResponse: {
            items: components["schemas"]["EventResponse"][];
        };
        EventPage: {
            items: components["schemas"]["EventResponse"][];
            /** @description Pass as `cursor` to get the next page; null on the last page. */
            nextCursor: string | null;
        };
        CreateEventDto: {
            /**
             * @default other
             * @enum {string}
             */
            category: "tech" | "music" | "food" | "sports" | "arts" | "networking" | "outdoors" | "other";
            /**
             * @description `draft` events are visible only to their host.
             * @default published
             * @enum {string}
             */
            status: "draft" | "published";
            /** @example Bangalore Backend Meetup */
            title: string;
            /** @example Talks on Postgres internals and NestJS at scale. */
            description?: string;
            /** @example 91springboard, Koramangala */
            location?: string;
            /**
             * @description ISO 8601, must be in the future.
             * @example 2026-10-10T12:30:00.000Z
             */
            startsAt: string;
            /**
             * @description ISO 8601, after startsAt.
             * @example 2026-10-10T15:30:00.000Z
             */
            endsAt: string;
            /**
             * @description Max attendees. Omit or null for unlimited.
             * @example 50
             */
            capacity?: number | null;
            /**
             * Format: uri
             * @description Online meeting link (https). Only people going and the host can see it.
             * @example https://meet.google.com/abc-defg-hij
             */
            meetingUrl?: string | null;
            /**
             * @description Remind attendees this many minutes before the start (5 min – 7 days). Omit or null for no reminder.
             * @example 60
             */
            reminderMinutes?: number | null;
        };
        UpdateEventDto: {
            /**
             * @default other
             * @enum {string}
             */
            category: "tech" | "music" | "food" | "sports" | "arts" | "networking" | "outdoors" | "other";
            /**
             * @description `draft` events are visible only to their host.
             * @default published
             * @enum {string}
             */
            status: "draft" | "published";
            /** @example Bangalore Backend Meetup */
            title?: string;
            /** @example Talks on Postgres internals and NestJS at scale. */
            description?: string;
            /** @example 91springboard, Koramangala */
            location?: string;
            /**
             * @description ISO 8601, must be in the future.
             * @example 2026-10-10T12:30:00.000Z
             */
            startsAt?: string;
            /**
             * @description ISO 8601, after startsAt.
             * @example 2026-10-10T15:30:00.000Z
             */
            endsAt?: string;
            /**
             * @description Max attendees. Omit or null for unlimited.
             * @example 50
             */
            capacity?: number | null;
            /**
             * Format: uri
             * @description Online meeting link (https). Only people going and the host can see it.
             * @example https://meet.google.com/abc-defg-hij
             */
            meetingUrl?: string | null;
            /**
             * @description Remind attendees this many minutes before the start (5 min – 7 days). Omit or null for no reminder.
             * @example 60
             */
            reminderMinutes?: number | null;
            /**
             * @description Optimistic lock: send the `version` you last read. If someone else edited
             *     the event since, you get 409 instead of silently overwriting their change.
             */
            version?: number;
        };
        RsvpResponse: {
            /**
             * @description `going` if you got a seat, `waitlisted` if the event is full.
             * @enum {string}
             */
            status: "going" | "waitlisted" | "cancelled";
            eventId: string;
            goingCount: number;
            /** @description null when capacity is unlimited */
            seatsLeft: number | null;
        };
        Attendee: {
            userId: string;
            name: string;
            /**
             * Format: date-time
             * @description When this person got their seat
             */
            joinedAt: string;
        };
        AttendeePage: {
            items: components["schemas"]["Attendee"][];
            total: number;
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    NotificationsController_list: {
        parameters: {
            query?: {
                /** @description Only unread notifications */
                unread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
        };
    };
    NotificationsController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
            /** @description Refresh token expired, reused or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    UsersController_hosting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEventsResponse"];
                };
            };
        };
    };
    UsersController_rsvps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyEventsResponse"];
                };
            };
        };
    };
    EventsController_list: {
        parameters: {
            query?: {
                category?: "tech" | "music" | "food" | "sports" | "arts" | "networking" | "outdoors" | "other";
                /** @description Only events starting at/after this time. Defaults to now. */
                from?: string;
                /** @description Only events starting before this time. */
                to?: string;
                /** @description Case-insensitive search on title and location. */
                q?: string;
                creatorId?: string;
                /** @description Opaque cursor from the previous page's `nextCursor`. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    EventsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_calendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description iCalendar file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Not the host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stale version, or capacity below attendees */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RsvpsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsvpResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Event cancelled or already started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RsvpsController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RsvpResponse"];
                };
            };
            /** @description You haven't RSVP'd */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RsvpsController_waitlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendeePage"];
                };
            };
            /** @description Not the host */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RsvpsController_attendees: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendeePage"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
